import Foundation
import SwiftUI
import Combine

// MARK: - Localization
struct Localizable {
    enum Language: String, CaseIterable, Identifiable {
        case french = "fr"
        case english = "en"
        var id: String { rawValue }
        
        var flag: String {
            switch self {
            case .french: return "🇫🇷"
            case .english: return "🇬🇧"
            }
        }
        
        var displayName: String {
            switch self {
            case .french: return "Français"
            case .english: return "English"
            }
        }
    }
    
    static func text(_ key: String, language: Language) -> String {
        translations[language]?[key] ?? key
    }
    
    private static let translations: [Language: [String: String]] = [
        .french: [
            "title": "Journal de Trading Avancé",
            "subtitle": "Analysez vos performances Long et Short par système",
            "dashboard": "Dashboard",
            "systems": "Systèmes",
            "trades": "Trades",
            "exchanges": "Exchanges",
            "newTrade": "Nouveau Trade",
            "newSystem": "Nouveau Système",
            "detailed": "Détaillé",
            "flash": "Flash",
            "date": "Date",
            "asset": "Actif",
            "type": "Type",
            "entryPrice": "Prix entrée",
            "exitPrice": "Prix sortie",
            "quantity": "Quantité",
            "leverage": "Levier",
            "orderType": "Type d'ordre",
            "system": "Système",
            "session": "Session",
            "add": "Ajouter",
            "cancel": "Annuler",
            "mainMetrics": "Métriques Principales",
            "winRate": "Win Rate",
            "totalPnL": "P&L Total",
            "payoffRatio": "Payoff Ratio",
            "fees": "Frais",
            "advancedMetrics": "Métriques Avancées",
            "maxDrawdown": "Drawdown Max",
            "sharpeRatio": "Sharpe Ratio",
            "expectancy": "Expectancy",
            "bestStreak": "Meilleure Série",
            "longPerf": "Performance LONG",
            "shortPerf": "Performance SHORT",
            "avgWin": "Avg Win",
            "pnlCurve": "Courbe de P&L",
            "perfBySession": "Performance par Session",
            "perfByAsset": "Performance par Actif",
            "long": "Long",
            "short": "Short",
            "taker": "Taker",
            "maker": "Maker",
            "pnlAmount": "P&L ($)",
            "fillAllFields": "Veuillez remplir tous les champs",
            "exchangeName": "Nom de l'exchange",
            "makerFee": "Maker Fee (%)",
            "takerFee": "Taker Fee (%)",
            "priority": "PRIORITAIRE",
            "setPriority": "Définir comme prioritaire",
            "systemName": "Nom du système",
            "systemExists": "Ce système existe déjà",
            "exportCSV": "Exporter CSV",
            "importCSV": "Importer CSV",
            "addSystem": "Ajouter un système",
            // Navigation
            "ai": "IA",
            "assistant": "Assistant",
            // Dashboard
            "performanceByDay": "Performance par Jour",
            "mondayToSunday": "Lundi → Dimanche",
            "advancedAnalytics": "Analyses avancées",
            // Analytics section
            "advancedAnalyticsTitle": "Analyses Avancées",
            "advancedAnalyticsSubtitleDetail": "Analysez vos performances en détail",
            "performanceByMonth": "Performance par Mois",
            "gains": "Gains",
            "pertes": "Pertes",
            "bestMonth": "Meilleur Mois",
            "worstMonth": "Pire Mois",
            "average": "Moyenne",
            // Analytics tabs
            "tabAnalytics": "Analytics",
            "tabMetrics": "Métriques",
            "tabCalendar": "Calendrier",
            // Emotional Summary card titles
            "cardAverageState": "État Moyen",
            "cardEmotionImpact": "Impact Émotions",
            "cardEmotionalRisk": "Risque Émotionnel",
            "cardAIAdvice": "Conseil IA",
            // Emotional states
            "stateConfident": "Confiant",
            "stateStressed": "Stressé",
            "stateAgitated": "Agité",
            "stateNeutral": "Neutre",
            // Impact states
            "impactInsufficient": "Insuffisant",
            "impactHighStress": "Stress élevé",
            "impactHighConf": "Confiance élevée",
            "impactInstability": "Instabilité",
            "impactBalanced": "Équilibré",
            "impactPositive": "Positif",
            "impactNegative": "Négatif",
            // Risk states
            "riskCritical": "Critique",
            "riskAttention": "Attention",
            "riskStable": "Stable",
            // Advice states
            "adviceStop": "Stopper",
            "advicePause": "Pause",
            "adviceReduce": "Réduire",
            "adviceStudy": "Étudier",
            "adviceContinue": "Continuer",
            // Emotional descriptions
            "descExcellent10": "Performance excellente sur 10 derniers trades",
            "descBalanced10": "Performance équilibrée sur 10 derniers trades",
            "descDifficult10": "Période difficile sur 10 derniers trades",
            "descNoData": "Pas assez de données pour analyser l\u{2019}état émotionnel",
            "descNoImpactData": "Pas assez de données pour analyser l\u{2019}impact émotionnel",
            "descConsecLoss": "Série de {n} pertes consécutives - Stress émotionnel élevé",
            "descConsecWin": "Série de {n} gains consécutifs - Confiance élevée",
            "descVolatility": "Volatilité P&L élevée ({v}) - Instabilité émotionnelle",
            "descBalancedStable": "Performance équilibrée - Émotions stables",
            "descCorrPositive": "Émotions positives corrélées aux gains (+{pct}%)",
            "descCorrNegative": "Émotions négatives corrélées aux pertes (-{pct}%)",
            "descNoCorrPnl": "Pas de corrélation claire entre émotions et P&L",
            "descRiskCritical": "Série de pertes importante ({n}) - Attention requise",
            "descRiskAttention": "Quelques pertes consécutives ({n}) - Vigilance",
            "descRiskStable": "Pas de série de pertes - Situation stable",
            "advicePauseDesc": "Prenez du recul et analysez vos stratégies",
            "adviceStudyDesc": "Étudiez vos patterns et améliorez votre approche",
            "adviceContinueDesc": "Continuez avec votre stratégie actuelle",
            "descEmoPosPercent": "{pct}% d\u{2019}émotions positives sur {n} entrées",
            "descEmoNegPercent": "{pct}% d\u{2019}émotions négatives sur {n} entrées",
            "descEmoMixPercent": "{pct}% d\u{2019}émotions mixtes sur {n} entrées",
            "emotions": "Émotions",
            "emotionalSummary": "Bilan émotionnel et impact",
            "heatmap": "Heatmap",
            "heatmapPreview": "Aperçu (4 semaines)",
            "newSession": "Nouvelle session",
            "sections": "section",
            "sectionsPlural": "sections",
            // Jours de la semaine
            "monday": "Lun",
            "tuesday": "Mar",
            "wednesday": "Mer",
            "thursday": "Jeu",
            "friday": "Ven",
            "saturday": "Sam",
            "sunday": "Dim",
            // IA Assistant
            "insights": "Insights",
            "conseils": "Conseils",
            "analyse": "Analyse",
            "indicateurs": "Indicateurs",
            "photo": "Photo",
            "calendar": "Calendrier",
            "lastUpdate": "Dernière mise à jour",
            "refresh": "Rafraîchir",
            "refreshing": "Actualisation...",
            "refreshAnalytics": "Rafraîchir les analyses IA",
            // Photo Analysis
            "photoAnalysis": "Analyse Photo",
            "photoAnalysisTitle": "PHOTO",
            "photoAnalysisInstructions": "Prenez une photo ou sélectionnez un graphique pour une analyse IA automatique.",
            "photoAnalysisInstructionsMulti": "Ajoutez une ou plusieurs photos de graphiques sur différentes unités de temps. Plus vous fournissez d'UT, plus l'analyse sera détaillée et précise.",
            "camera": "Appareil photo",
            "library": "Bibliothèque",
            "selectedImage": "Image sélectionnée",
            "selectedImages": "Images sélectionnées",
            "analyzing": "Analyse en cours...",
            "quickRead": "🔎 Lecture rapide du marché",
            "marketStructure": "🧱 Structure de marché",
            "keyZones": "📍 Zones clés",
            "trendMomentum": "📈 Tendance & Momentum",
            "patterns": "🕯️ Patterns & Chandeliers",
            "indicators": "📊 Indicateurs",
            "multiTimeframe": "🧭 Lecture Multi-Timeframe",
            "tradePlan": "🎯 Plan de trade",
            "marketPsychology": "🧠 Psychologie de marché",
            "bias": "Biais",
            "entry": "Entrée",
            "stopLoss": "Stop Loss",
            "targets": "Objectifs",
            "confirmation": "Confirmation",
            "invalidation": "Invalidation",
            // Multi-Timeframe Photo Analysis
            "multiTimeframeMode": "MULTI-UT",
            "selectTimeframePhoto": "Sélectionnez l'unité de temps",
            "addTimeframePhoto": "Ajouter une photo",
            "analyzeMulti": "Analyser Multi-UT",
            "analyzeSingle": "Analyser",
            "clearAll": "Tout effacer",
            "multiTimeframeInfo": "Mode Multi-UT activé — L'IA croisera les analyses entre les différentes unités de temps pour un résultat enrichi.",
            "analyzingMultiUT": "Analyse Multi-UT en cours...",
            "analyzingSingleUT": "Analyse IA en cours...",
            "imagesLoaded": "Images chargées",
            "crossReferencing": "Croisement des UT...",
            "detectingPatterns": "Détection des patterns...",
            "technicalAnalysis": "Analyse technique...",
            "confluenceDetection": "Détection des confluences...",
            "generatingReport": "Génération du rapport",
            "multiTimeframeAnalysis": "Analyse Multi-Timeframe",
            "utCount": "UT",
            "confluences": "Confluences inter-UT",
            "identifiedRisks": "Risques identifiés",
            "alternativeScenario": "Scénario alternatif",
            "riskReward": "R:R",
            "reversalZones": "Zones retournement",
            "chooseTimeframe": "Choisissez l'unité de temps",
            "chooseTimeframeSubtitle": "Sélectionnez l'UT correspondant à votre capture d'écran",
            "multiScanInProgress": "Scan Multi-UT en cours...",
            "singleScanInProgress": "Scan IA en cours...",
            "crossReferencingTimeframes": "L'IA croise les analyses entre les UT",
            "analyzingPatterns": "L'IA analyse les patterns, niveaux et structures",
            "apiKeyMissing": "Clé API OpenAI non configurée. Veuillez configurer votre clé dans les paramètres.",
            "analyzerInitError": "Impossible d'initialiser l'analyseur.",
            "analysisErrorGeneric": "Erreur lors de l'analyse :",
            "analysisError": "Erreur d'analyse",
            // Menu
            "profile": "Profil",
            "signOut": "Se déconnecter",
            "signIn": "Se connecter",
            "signUp": "S'inscrire",
            "storageSettings": "Paramètres Stockage",
            "manageSubscription": "Gérer l'abonnement PRO",
            "upgradeToPro": "Passer en PRO",
            "addTrade": "Ajouter un trade",
            "addTradeAccessibility": "Ajouter un trade",
            // Dashboard supplémentaires
            "performanceByHour": "Performance par Heure",
            "customizableRanges": "Plages modifiables • Ajoutez vos créneaux",
            "modify": "Modifier",
            "hourRange": "Plage horaire",
            "sessionsDescription": "Asie / Londres / New York • Personnalisable",
            "hourRanges": "Plages horaires",
            "hourRangesSubtitle": "Ajoutez / supprimez / modifiez vos créneaux",
            "sessions": "Sessions",
            "performanceLongShort": "Performance Long / Short",
            "performanceLongShortSubtitle": "Win rate & P&L par direction",
            "deepen": "Approfondir",
            "deepenSubtitle": "Analyses détaillées • Ouvre les sections avancées",
            "advancedMetricsSubtitle": "Drawdown, Sharpe, expectancy, streaks",
            "advancedAnalyticsSubtitle": "Analytics / métriques / calendrier",
            "pnlCurvePreview": "Aperçu (30 jours)",
            "server": "Serveur",
            
            // NAVIGATION & TABS
            "account": "Compte",
            
            // MÉTRIQUES SUPPLÉMENTAIRES
            "avgLoss": "Perte Moyenne",
            "totalTrades": "Trades Total",
            "winningTrades": "Trades Gagnants",
            "losingTrades": "Trades Perdants",
            
            // TRADES
            "save": "Enregistrer",
            "delete": "Supprimer",
            "edit": "Modifier",
            "tradeAdded": "Trade ajouté avec succès",
            "tradeDeleted": "Trade supprimé",
            "tradeUpdated": "Trade mis à jour",
            
            // SYSTÈMES
            "systemAdded": "Système ajouté",
            "systemDeleted": "Système supprimé",
            
            // ÉMOTIONS & ANALYTICS
            "emotionalAnalysis": "Analyse Émotionnelle",
            "emotionalJournal": "Journal Émotionnel",
            "emotionalLoad": "Charge émotionnelle",
            "emotionalBalance": "Équilibre émotionnel",
            "emotionalCorrelation": "Corrélation émotionnelle",
            "emotionImpact": "Impact émotionnel",
            "emotionCorrelationWithPnL": "Corrélation émotion/P&L",
            "stress": "Stress",
            "anxiety": "Anxiété",
            "confidence": "Confiance",
            "fear": "Peur",
            "greed": "Avidité",
            "discipline": "Discipline",
            "patience": "Patience",
            "impulsivity": "Impulsivité",
            "lowStress": "Stress faible",
            "moderateStress": "Stress modéré",
            "highStress": "Stress élevé",
            
            // INDICATEURS MTF
            "mtfDashboard": "Dashboard MTF",
            "timeframes": "Timeframes",
            "selectTimeframe": "Sélectionner un timeframe",
            "updateTimeframes": "Mettre à jour les timeframes",
            "5m": "5m",
            "15m": "15m",
            "1h": "1h",
            "4h": "4h",
            "1d": "1j",
            "synchronized": "Synchronisé",
            
            // RSI
            "rsi": "RSI",
            "rsiDashboard": "Dashboard RSI",
            "oversold": "Survendu",
            "overbought": "Suracheté",
            "neutral": "Neutre",
            "rsiValue": "Valeur RSI",
            
            // Scenario cards & analysis UI
            "bullishScenario": "Scénario Haussier",
            "bearishScenario": "Scénario Baissier",
            "stopLabel": "Stop",
            "objectivesLabel": "Objectifs",
            "riskLabel": "Risque",
            "potentialLabel": "Potentiel",
            "technicalAnalysisTitle": "Analyse Technique",
            "riskManagementTitle": "Gestion du Risque",
            "recommendedRisk": "Risque recommandé",
            "support1": "Support 1",
            "resistance1": "Résistance 1",
            "entryType": "Type",
            
            // VMC
            "vmc": "VMC",
            "vmcDashboard": "Dashboard VMC",
            "trend": "Tendance",
            "bullish": "Haussier",
            "bearish": "Baissier",
            "ranging": "Range",
            "strength": "Force",
            "weak": "Faible",
            "moderate": "Modéré",
            "strong": "Fort",
            
            // WAVE TREND
            "waveTrend": "Wave Trend",
            "wtDashboard": "Dashboard WT",
            "crossover": "Croisement",
            "divergence": "Divergence",
            "bullishDivergence": "Divergence haussière",
            "bearishDivergence": "Divergence baissière",
            
            // COMBINAISON INDICATEURS
            "combinedIndicators": "Indicateurs Combinés",
            "alignmentScore": "Score d'alignement",
            "confluence": "Confluence",
            
            // CALENDRIER ÉCONOMIQUE
            "economicCalendar": "Calendrier Économique",
            "upcomingEvents": "Événements à venir",
            "pastEvents": "Événements passés",
            "impact": "Impact",
            "highImpact": "Impact élevé",
            "mediumImpact": "Impact moyen",
            "lowImpact": "Impact faible",
            "forecast": "Prévision",
            "previous": "Précédent",
            "actual": "Actuel",
            "country": "Pays",
            "event": "Événement",
            "time": "Heure",
            "noEventsToday": "Aucun événement aujourd'hui",
            "loadingEvents": "Chargement des événements...",
            "refreshCalendar": "Actualiser le calendrier",
            
            // GAMIFICATION
            "challenges": "Défis",
            "missions": "Missions",
            "badges": "Badges",
            "level": "Niveau",
            "xp": "XP",
            "experience": "Expérience",
            "progress": "Progression",
            "rewards": "Récompenses",
            "unlocked": "Débloqué",
            "locked": "Verrouillé",
            "complete": "Compléter",
            "completed": "Complété",
            "inProgress": "En cours",
            "notStarted": "Pas commencé",
            "streak": "Série",
            "dailyStreak": "Série quotidienne",
            "currentStreak": "Série actuelle",
            
            // SOCIAL & VERIFICATION
            "socialVerification": "Vérification Sociale",
            "verifyAccount": "Vérifier le compte",
            "verified": "Vérifié",
            "notVerified": "Non vérifié",
            "connectSocialAccount": "Connecter un compte social",
            "shareResults": "Partager les résultats",
            "leaderboard": "Classement",
            "rank": "Rang",
            "followers": "Abonnés",
            "following": "Abonnements",
            
            // ALERTES & NOTIFICATIONS
            "alerts": "Alertes",
            "createAlert": "Créer une alerte",
            "editAlert": "Modifier l'alerte",
            "deleteAlert": "Supprimer l'alerte",
            "alertName": "Nom de l'alerte",
            "condition": "Condition",
            "price": "Prix",
            "priceAbove": "Prix au-dessus de",
            "priceBelow": "Prix en-dessous de",
            "volume": "Volume",
            "triggerPrice": "Prix de déclenchement",
            "triggered": "Déclenché",
            "active": "Actif",
            "inactive": "Inactif",
            "notifications": "Notifications",
            "pushNotifications": "Notifications push",
            "emailNotifications": "Notifications email",
            "soundEnabled": "Son activé",
            
            // STATS AVANCÉES
            "profitFactor": "Profit Factor",
            "riskRewardRatio": "Ratio Risque/Rendement",
            "averageRR": "R:R Moyen",
            "recoveryFactor": "Recovery Factor",
            "kellyPercentage": "Kelly %",
            "consistency": "Constance",
            "volatility": "Volatilité",
            "standardDeviation": "Écart-type",
            "calmarRatio": "Calmar Ratio",
            "sortinoRatio": "Sortino Ratio",
            
            // PARAMÈTRES
            "settings": "Paramètres",
            "aiSettings": "Paramètres IA",
            "language": "Langue",
            "selectLanguage": "Choisir la langue",
            "theme": "Thème",
            "appearance": "Apparence",
            "darkMode": "Mode sombre",
            "lightMode": "Mode clair",
            "automatic": "Automatique",
            "currency": "Devise",
            "timezone": "Fuseau horaire",
            "dateFormat": "Format de date",
            "timeFormat": "Format d'heure",
            "chartType": "Type de graphique",
            "candlestick": "Chandeliers",
            "line": "Ligne",
            "bar": "Barres",
            "area": "Zone",
            
            // AUTH
            "email": "Email",
            "password": "Mot de passe",
            "confirmPassword": "Confirmer le mot de passe",
            "forgotPassword": "Mot de passe oublié ?",
            "resetPassword": "Réinitialiser",
            "createAccount": "Créer un compte",
            "alreadyHaveAccount": "Vous avez déjà un compte ?",
            "dontHaveAccount": "Vous n'avez pas de compte ?",
            
            // SUBSCRIPTION
            "subscription": "Abonnement",
            "freePlan": "Plan Gratuit",
            "proPlan": "Plan PRO",
            "subscribe": "S'abonner",
            
            // JOURS COMPLETS
            "mondayFull": "Lundi",
            "tuesdayFull": "Mardi",
            "wednesdayFull": "Mercredi",
            "thursdayFull": "Jeudi",
            "fridayFull": "Vendredi",
            "saturdayFull": "Samedi",
            "sundayFull": "Dimanche",
            
            // TEMPS
            "today": "Aujourd'hui",
            "yesterday": "Hier",
            "thisWeek": "Cette semaine",
            "lastWeek": "Semaine dernière",
            "thisMonth": "Ce mois",
            "lastMonth": "Mois dernier",
            "all": "Tout",
            
            // MESSAGES & ERREURS
            "error": "Erreur",
            "success": "Succès",
            "warning": "Attention",
            "loading": "Chargement...",
            "noData": "Aucune donnée",
            "noResults": "Aucun résultat",
            "tryAgain": "Réessayer",
            "close": "Fermer",
            "confirm": "Confirmer",
            "yes": "Oui",
            "no": "Non",
            "ok": "OK",
            
            // RECHERCHE & FILTRES
            "search": "Rechercher",
            "filter": "Filtrer",
            "sort": "Trier",
            "sortBy": "Trier par",
            "filterBy": "Filtrer par",
            "none": "Aucun",
            "select": "Sélectionner",
            "clear": "Effacer",
            
            // SÉCURITÉ
            "security": "Sécurité",
            "privacy": "Confidentialité",
            "biometricAuth": "Auth. biométrique",
            "faceID": "Face ID",
            "touchID": "Touch ID",
            "pinCode": "Code PIN",
            "changePIN": "Modifier le PIN",
            "twoFactorAuth": "Auth. à 2 facteurs",
            "enable": "Activer",
            "disable": "Désactiver",
            "deleteAccount": "Supprimer le compte",
            "deleteAccountWarning": "Cette action est irréversible",
            
            // IMPORT/EXPORT
            "import": "Importer",
            "export": "Exporter",
            "backup": "Sauvegarde",
            "restore": "Restaurer",
            "downloadBackup": "Télécharger la sauvegarde",
            "uploadBackup": "Charger une sauvegarde",
            "selectFile": "Sélectionner un fichier",
            "lastBackup": "Dernière sauvegarde",
            "autoBackup": "Sauvegarde auto",
            "backupFrequency": "Fréquence de sauvegarde",
            "daily": "Quotidien",
            "weekly": "Hebdomadaire",
            "monthly": "Mensuel",
            "dataExport": "Export de données",
            "dataImport": "Import de données",
            
            // CHARTS
            "chartSettings": "Paramètres graphique",
            "showGrid": "Afficher la grille",
            "showVolume": "Afficher le volume",
            "showMA": "Afficher les MA",
            "showBollinger": "Afficher Bollinger",
            "showRSI": "Afficher RSI",
            "showMACD": "Afficher MACD",
            "colorScheme": "Schéma de couleurs",
            "greenRed": "Vert/Rouge",
            "blueOrange": "Bleu/Orange",
            "custom": "Personnalisé",
            
            // HELP & SUPPORT
            "help": "Aide",
            "support": "Support",
            "faq": "FAQ",
            "tutorials": "Tutoriels",
            "contactUs": "Nous contacter",
            "reportBug": "Signaler un bug",
            "featureRequest": "Demander une fonctionnalité",
            "documentation": "Documentation",
            "termsOfService": "Conditions d'utilisation",
            "privacyPolicy": "Politique de confidentialité",
            "version": "Version",
            "buildNumber": "Numéro de build",
            
            // AUTRES
            "local": "Local",
            "sync": "Synchroniser",
            "syncing": "Synchronisation...",
            "offline": "Hors ligne",
            "online": "En ligne",
            
            // TEXTES SPÉCIFIQUES DES VUES (extraits automatiquement)
            "addTrades": "Ajouter des trades",
            "aiAnalysis": "Analyse IA",
            "analysisWaiting": "Analyse en attente...",
            "analysisInProgress": "Analyse en cours...",
            "advancedTechnicalAnalysis": "Analyse technique avancée en cours...",
            "emotionalAnalyses": "Analyses Émotionnelles",
            "badge": "Badge",
            "loadingWaveTrend": "Chargement de l'oscillateur Wave Trend...",
            "loadingEnrichedData": "Chargement des données pour l'analyse enrichie...",
            "loadingMTFIndicators": "Chargement des indicateurs MTF (RSI + VMC)...",
            "loadingIndicators": "Chargement des indicateurs...",
            "loadingProducts": "Chargement des produits...",
            "aiChat": "Chat IA",
            "aiCoach": "Coach IA",
            "configuration": "Configuration",
            "curve": "Courbe",
            "alertDetail": "Détail de l'alerte",
            "tradeDetail": "Détail du Trade",
            "details": "Détails",
            "exportImport": "Export / Import",
            "exporting": "Export en cours...",
            "filters": "Filtres",
            "advancedFilters": "Filtres Avancés",
            "generatingHeatmap": "Génération de la heatmap...",
            "performanceHeatmaps": "Heatmaps de Performance",
            "history": "Historique",
            "aiAndOpenAI": "IA & OpenAI",
            "importing": "Import en cours...",
            "aiAnalyzingChart": "L'IA analyse votre graphique...",
            "mission": "Mission",
            "storageMode": "Mode de stockage",
            "editExchange": "Modifier l'Exchange",
            "editTrade": "Modifier le Trade",
            "myAccount": "Mon compte",
            "newExchange": "Nouvel Exchange",
            "pnlWithContext": "P&L avec Contexte",
            "alertSettings": "Paramètres Alertes",
            "referral": "Parrainage",
            "moreOptions": "Plus d'options",
            "saveFilter": "Sauvegarder le filtre",
            "statistics": "Statistiques",
            "storage": "Stockage",
            "writeMessage": "Écrire un message...",
            "emotionsPerformance": "Émotions ↔ Performance",
            "waveTrendOscillator": "Wave Trend Oscillator",
            "DonnesTechniques": "Données Techniques",
            "alertes": "Alertes",
            "conf": "Conf.",
            "extrmesBas": "Extrêmes Bas",
            "extrmesHauts": "Extrêmes Hauts",
            "global": "Global",
            "guide": "Guide",
            "intqualityscore": "Score de Qualité",
            "intsnapshotconfluencepercent": "Confluence",
            "lgende": "Légende",
            "momentum": "Momentum",
            "mtf": "MTF",
            "pourLesCurieux": "Pour les Curieux",
            "score": "Score",
            "scoreCombin": "Score Combiné",
            "signal": "Signal",
            "signalGlobal": "Signal Global",
            "signaux": "Signaux",
            "synthse": "Synthèse",
            "unitDeTemps": "Unité de Temps",
            "volume24h": "Volume 24h",
            "btcusdt": "BTCUSDT",
            "disponibleAvecLabonnementPremium": "Disponible avec l'abonnement Premium",
            "labelvalue100": "Label (Valeur /100)",
            "scoremotionnelemotionscore100": "Score Émotionnel",
            "name": "Nom",
            "499moisAnnulationToutMoment": "4,99€/mois · Annulation à tout moment",
            "Obligations": "Obligations",
            "Recommandation": "Recommandation",
            "Recommandations": "Recommandations",
            "Records": "Records",
            "accdezToutesLesFonctionnalitsAvancesAvecLePassPro": "Accédez à toutes les fonctionnalités avancées avec le Pass Pro",
            "accsDepuisNimporteO": "Accès depuis n'importe où",
            "actions": "Actions",
            "actionsRapides": "Actions rapides",
            "afficherLeContextemotionnel": "Afficher le contexte émotionnel",
            "agrgation": "Agrégation",
            "ajouterUneEmotion": "Ajouter une émotion",
            "aperu": "Aperçu",
            "appareil": "Appareil",
            "apple": "Apple",
            "aprs": "Après",
            "aucunBadge": "Aucun badge",
            "aucunBadgeDbloqu": "Aucun badge débloqué",
            "aucunDfiDisponible": "Aucun défi disponible",
            "aucunFilleulPourLinstant": "Aucun filleul pour l'instant",
            "aucunInsightDisponiblePourCettePriode": "Aucun insight disponible pour cette période",
            "aucunTrade": "Aucun trade",
            "aucunTradeTrouv": "Aucun trade trouvé",
            "aucuneEntre": "Aucune entrée",
            "aucuneProgression": "Aucune progression",
            "aucuntatEnregistr": "Aucun état enregistré",
            "aucunvnementTrouv": "Aucun événement trouvé",
            "aucunvnementXp": "Aucun événement XP",
            "avant": "Avant",
            "avecContextemotionnelEnArrireplan": "Avec contexte émotionnel en arrière-plan",
            "badgeDbloqu": "Badge débloqué !",
            "badgesParRaret": "Badges par rareté",
            "badgesRcents": "Badges récents",
            "bilanmotionnel": "Bilan émotionnel",
            "bonjour": "Bonjour",
            "calculEnCours": "Calcul en cours...",
            "calculerPl": "Calculer P&L",
            "calculsAutomatiques": "Calculs automatiques",
            "cart": "Écarté",
            "cesFiltresSerontAppliqusParDfautLorsDeLouvertureDeLaListeDesAlertes": "Ces filtres seront appliqués par défaut lors de l'ouverture de la liste des alertes",
            "cesStatistiquesVousDonnentUneVueDensembleDeVosDonnesStockes": "Ces statistiques vous donnent une vue d'ensemble de vos données stockées",
            "changerLaPhoto": "Changer la photo",
            "chargemotionnelle": "Charge émotionnelle",
            "chargemotionnelle0100": "Charge émotionnelle (0-100)",
            "choisirLeModeDeStockage": "Choisir le mode de stockage",
            "choisissezEntreLeStockageLocalprivOuFirebasesynchronis": "Choisissez entre le stockage local (privé) ou Firebase (synchronisé)",
            "choisissezVotreAbonnement": "Choisissez votre abonnement",
            "choisissezVotreMthodeDajout": "Choisissez votre méthode d'ajout",
            "codeDeVrification": "Code de vérification",
            "commencezTraderPourGagnerDeLxp": "Commencez à trader pour gagner de l'XP",
            "commentAccderAuPrestige": "Comment accéder au prestige",
            "commentDbloquer": "Comment débloquer",
            "comparezVosmotionsEtVosPerformancesQuotidiennes": "Comparez vos émotions et vos performances quotidiennes",
            "conditions": "Conditions",
            "configurezCetteUrlDansTradingviewPourRecevoirDesAlertesAutomatiquementLaClSecrteDoitCorrespondreCelleConfigureSurLeServeur": "Configurez cette URL dans TradingView pour recevoir des alertes automatiquement. La clé secrète doit correspondre à celle configurée sur le serveur.",
            "connectezvousPourAccderVotreJournalDeTrading": "Connectez-vous pour accéder à votre journal de trading",
            "conseilPro": "Conseil Pro",
            "contexte": "Contexte",
            "continuer": "Continuer",
            "copier": "Copier",
            "corrlationmotionperformance": "Corrélation émotion/performance",
            "courbe": "Courbe",
            "courbeDePlCumul": "Courbe de P&L cumulé",
            "crationDeTrade": "Création de trade",
            "crerUnTrade": "Créer un trade",
            "dbloquLe": "Débloqué le",
            "dbloquezDesBadgesEnCompltantDesDfis": "Débloquez des badges en complétant des défis",
            "dbloquezToutLePotentiel": "Débloquez tout le potentiel",
            "dcomposition": "Décomposition",
            "dernireEntre": "Dernière entrée",
            "description": "Description",
            "dfisActifs": "Défis actifs",
            "direction": "Direction",
            "donnesMigrer": "Données à migrer",
            "donnesTechniques": "Données techniques",
            "dupliquerLeTrade": "Dupliquer le trade",
            "enContinuantTuUtilisesFirebaseAuthentication": "En continuant, tu utilises Firebase Authentication",
            "enregistrezUnTradeEnQuelquesSecondes": "Enregistrez un trade en quelques secondes",
            "enregistrezVosTransactionsDeTrading": "Enregistrez vos transactions de trading",
            "enregistrezVotretatmotionnelActuel": "Enregistrez votre état émotionnel actuel",
            "entrezLeCode": "Entrez le code",
            "essayerProGratuit": "Essayer Pro gratuitement",
            "europe": "Europe",
            "exchangeParDfaut": "Exchange par défaut",
            "exit": "Sortie",
            "exporterLesDonnes": "Exporter les données",
            "filtresParDfaut": "Filtres par défaut",
            "fonctionnalitsPro": "Fonctionnalités Pro",
            "galerie": "Galerie",
            "gnral": "Général",
            "google": "Google",
            "heatmapDePerformance": "Heatmap de performance",
            "heuresSilencieuses": "Heures silencieuses",
            "historiqueXpRcent": "Historique XP récent",
            "impactSurLaPerformance": "Impact sur la performance",
            "importerLesDonnes": "Importer les données",
            "impossibleDeChargerLesProduits": "Impossible de charger les produits",
            "inclusDansLePassPro": "Inclus dans le Pass Pro",
            "informations": "Informations",
            "instructions": "Instructions",
            "intense": "Intense",
            "intensit": "Intensité",
            "interprtation": "Interprétation",
            "leModeLocalStockeLesDonnesUniquementSurVotreAppareilLeModeFirebaseSynchroniseVosDonnesDansLeCloud": "Le mode local stocke les données uniquement sur votre appareil. Le mode Firebase synchronise vos données dans le Cloud.",
            "leStockageLocalGardeVosAlertesPrivesSurCetAppareilUniquement": "Le stockage local garde vos alertes privées sur cet appareil uniquement",
            "lesAlertesSontStockesUniquementSurCetAppareilEllesNeSerontPasSynchronisesAvecDautresAppareils": "Les alertes sont stockées uniquement sur cet appareil. Elles ne seront pas synchronisées avec d'autres appareils.",
            "levier": "Levier",
            "lgendemotionnelle": "Légende émotionnelle",
            "lissePourRvlerLaTendanceSansJugement": "Lissée pour révéler la tendance, sans jugement",
            "lues": "Lues",
            "message": "Message",
            "mexc": "MEXC",
            "migration": "Migration",
            "migrationDesDonnes": "Migration des données",
            "migrezVosDonnesEntreLesDiffrentsModesDeStockageCetteOprationPeutPrendreQuelquesMinutes": "Migrez vos données entre les différents modes de stockage. Cette opération peut prendre quelques minutes.",
            "modeDeStockage": "Mode de stockage",
            "mom": "Mom.",
            "momentumTrsFortRisqueDeRetournement": "Momentum très fort, risque de retournement",
            "motion": "Émotion",
            "motionDominante": "Émotion dominante",
            "motionnel": "Émotionnel",
            "motionsPerformance": "Émotions ↔ Performance",
            "mthodesDeVrification": "Méthodes de vérification",
            "mtrique": "Métrique",
            "mtriquesAvances": "Métriques avancées",
            "mtriquesCls": "Métriques clés",
            "multiappareils": "Multi-appareils",
            "niveauDeContrle": "Niveau de contrôle",
            "niveauDePrestige": "Niveau de prestige",
            "niveaux": "Niveaux",
            "number": "Numéro",
            "options": "Options",
            "ouDbloquezInstantanmentAvecLePassPro": "Ou débloquez instantanément avec le Pass Pro",
            "partager": "Partager",
            "partagezVotreCodePourInviterDesAmisEtGagnerDesRcompenses": "Partagez votre code pour inviter des amis et gagner des récompenses",
            "pasEncoreAssezDentresAftertradePourCalculerLaCharge": "Pas encore assez d'entrées after-trade pour calculer la charge",
            "pasEncoreDeDonnesDeCorrlation": "Pas encore de données de corrélation",
            "pasEncoreDeDonnesPl": "Pas encore de données P&L",
            "pasEncoreDeDonnesmotionnelles": "Pas encore de données émotionnelles",
            "passezAuNiveauSuprieurAvecLePassPro": "Passez au niveau supérieur avec le Pass Pro",
            "pendantLesHeuresSilencieusesSeulesLesAlertesDeHautePrioritSerontEnvoyes": "Pendant les heures silencieuses, seules les alertes de haute priorité seront envoyées",
            "performancePl": "Performance P&L",
            "performanceTempsRel": "Performance temps réel",
            "pl": "P&L",
            "plCumul": "P&L Cumulé",
            "plCumulatif7Jours": "P&L cumulatif 7 jours",
            "plDuJour": "P&L du jour",
            // CurveMode titles
            "curveModePnl": "P&L",
            "curveModeEmotional": "Charge émotionnelle",
            "curveModeCorrelation": "Corrélation",
            "curveModePnlContext": "P&L + Contexte",
            // Curve subtitles
            "curveSubPnl": "Résultat (P&L)",
            "curveSubEmotional": "Contexte (pression)",
            "curveSubCorrelation": "P&L × émotion",
            "curveSubPnlContext": "P&L + contexte émotionnel",
            // Curve helper texts
            "curveHelperPnl": "Cette courbe montre l\u{2019}évolution cumulée de tes résultats.",
            "curveHelperEmotional": "La charge émotionnelle représente une pression mentale, pas une performance.",
            "curveHelperCorrelation": "Cette vue permet d\u{2019}observer si tes pertes ou gains surviennent en contexte émotionnel élevé.",
            "curveHelperPnlContext": "Les barres représentent le résultat par période. La courbe indique le niveau de pression émotionnelle.",
            // Insights toggle
            "showInsights": "Voir l\u{2019}analyse",
            "hideInsights": "Masquer l\u{2019}analyse",
            // Correlation labels
            "corrStrong": "Corrélation forte",
            "corrModerate": "Corrélation modérée",
            "corrWeak": "Corrélation faible",
            "corrNone": "Pas de corrélation",
            "corrNegWeak": "Corrélation négative faible",
            "corrNegModerate": "Corrélation négative modérée",
            "corrNegStrong": "Corrélation négative forte",
            // Insight texts (DashboardAnalyticsCompute)
            "insightPnlLastSegmentUp": "Environ {pct} % de la performance se construit en fin de période.",
            "insightPnlLastSegmentNet": "Environ {pct} % du mouvement net se concentre en fin de période.",
            "insightPnlTrendUp": "La courbe est majoritairement ascendante sur cette période.",
            "insightPnlTrendDown": "La courbe est majoritairement descendante sur cette période.",
            "insightPnlDrawdown": "Les drawdowns les plus longs surviennent en {placement} de période.",
            "insightEmoCalmShare": "{pct} % du temps est passé en zone Calme / Attention.",
            "insightEmoTensionShare": "La pression dépasse Tension sur {pct} % de la période.",
            "insightEmoSpikes": "Les pics émotionnels sont courts mais fréquents.",
            "insightCorrLossHighPressure": "{pct} % des pertes surviennent lorsque la pression dépasse Tension.",
            "insightCorrGainsCalm": "Les gains sont principalement réalisés en zone Calme.",
            "insightCorrPerformancePressure": "La performance tend à diminuer lorsque la pression dépasse Tension.",
            "periodStart": "début",
            "periodEnd": "fin",
            "plPriode": "P&L période",
            "plQuotidien": "P&L quotidien",
            "plateforme": "Plateforme",
            "pointSlectionn": "Point sélectionné",
            "prcdent": "Précédent",
            "presetsRapides": "Presets rapides",
            "pressionmotionnelle0100": "Pression émotionnelle (0-100)",
            "prestige": "Prestige",
            "prestigeMaximumAtteint": "Prestige maximum atteint",
            "priode": "Période",
            "priodesRapides": "Périodes rapides",
            "progression": "Progression",
            "progressionVersLePrestige": "Progression vers le prestige",
            "prtrade": "Par trade",
            "prvision": "Prévision",
            "reco": "Reco.",
            "recommandation": "Recommandation",
            "recommandations": "Recommandations",
            "recommandationsGnrales": "Recommandations générales",
            "rejoindre": "Rejoindre",
            "rel": "Réel",
            "reroll": "Relancer",
            "rerolls": "Relances",
            "restaurationComplte": "Restauration complète",
            "restaurerLesAchats": "Restaurer les achats",
            "rleDordre": "Règle d'ordre",
            "rsumQuotidien": "Résumé quotidien",
            "sauvegardeComplte": "Sauvegarde complète",
            "sauvegardeEtRestauration": "Sauvegarde et restauration",
            "scnarios": "Scénarios",
            "scoreDeDiscipline": "Score de discipline",
            "sentiment": "Sentiment",
            "siConsensus": "Si consensus",
            "signalLine": "Signal Line",
            "slectionMultipleDeSymboles": "Sélection multiple de symboles",
            "slectionnezLesTimeframes": "Sélectionnez les timeframes",
            "slectionnezUnePhotoDeGraphique": "Sélectionnez une photo de graphique",
            "source": "Source",
            "stabilitmotionnelle": "Stabilité émotionnelle",
            "statistiques": "Statistiques",
            "statistiquesDuJour": "Statistiques du jour",
            "statistiquesGlobales": "Statistiques globales",
            "statutDeLecture": "Statut de lecture",
            "step": "Étape",
            "stockageDesAlertes": "Stockage des alertes",
            "stockageLocalUniquement": "Stockage local uniquement",
            "surprise": "Surprise",
            "svrit": "Sévérité",
            "symbole": "Symbole",
            "symbolesRcents": "Symboles récents",
            "tags": "Tags",
            "tapes": "Étapes",
            "termin": "Terminé",
            "timelineDes10DerniersJours": "Timeline des 10 derniers jours",
            "total": "Total",
            "touchezEtGlissezSurLeGraphiquePourExplorerLesDonnes": "Touchez et glissez sur le graphique pour explorer les données",
            "touchezGlissez": "Touchez & glissez",
            "touchezUneCase": "Touchez une case",
            "tous": "Tous",
            "toutes": "Toutes",
            "toutesVosDonnesSerontExportes": "Toutes vos données seront exportées",
            "tradeLi": "Trade lié",
            "uidFirebase": "UID Firebase",
            "valeurMax": "Valeur max",
            "valeurMin": "Valeur min",
            "valeurs": "Valeurs",
            "valider": "Valider",
            "voirTout": "Voir tout",
            "volutionDeLintensit": "Évolution de l'intensité",
            "volutionXp7Jours": "Évolution XP 7 jours",
            "vosDonnesToujoursJour": "Vos données toujours à jour",
            "vosFilleuls": "Vos filleuls",
            "vousNavezPasReuLeCode": "Vous n'avez pas reçu le code ?",
            "zonesDeVigilance": "Zones de vigilance",
            "zonesDeVigilanceAvecLissagePourRvlerLesTendances": "Zones de vigilance avec lissage pour révéler les tendances",
            // AIAssistantView - Insights tab
            "predictionNextTrade": "Prédiction Prochain Trade",
            "basedOnHistory": "Basé sur ton historique et contexte actuel",
            "winProbability": "Probabilité de gain",
            "maxLoss": "Perte max",
            "maxGain": "Gain max",
            "expectedValue": "Espérance mathématique",
            "influencingFactors": "Facteurs influents",
            "recommendation": "Recommandation",
            "planConsistency": "Cohérence du Plan",
            "respectStrategy": "Respect de ta stratégie",
            "adherence": "Adhérence",
            "aiRecommendations": "Recommandations IA",
            "optimalTiming": "Timing Optimal",
            "bestMomentsToTrade": "Meilleurs moments pour trader",
            "bestHour": "Meilleure heure",
            "avoidHour": "Éviter",
            "bestDay": "Meilleur jour",
            "recommendations": "Recommandations",
            "preferablyTrade": "Trade préférentiellement entre",
            // AIAssistantView - Advice tab
            "currentStatus": "Statut Actuel",
            "edgeScore": "Edge Score",
            "priorityAction": "Action Prioritaire",
            "recommendedAction": "Action recommandée",
            "optimalWindow": "Fenêtre Optimale",
            "timingEdge": "Timing de ton edge",
            "dailyFocus": "Focus du Jour",
            "prioritySetup": "Setup prioritaire",
            "influencingFactorsPlural": "Facteurs Influents",
            "evaluatingConditions": "Évaluation de tes conditions",
            "currentEdgeAdvantages": "Avantages actuels",
            "riskToWatch": "Risques à surveiller",
            "edgeScoreExplanation": "Comment est calculé ton Edge Score ?",
            "edgeScoreFormula": "Score = 50 +",
            "baselinePoints": "Le calcul commence à 50 points de base, puis des ajustements sont appliqués selon tes conditions actuelles :",
            "decisionLevels": "Les paliers de décision",
            "factorsInfluencingEdge": "Facteurs qui influencent ton Edge",
            // AIAssistantView - Indicators tab
            "tiltDetected": "ALERTE TILT DÉTECTÉ",
            "streakAndTiltAnalysis": "Analyse Streak & Tilt",
            "behaviorAfterTrades": "Comportement après trades",
            "behaviorAfterWinsLosses": "Comportement après wins/losses",
            "revengeTradesDetected": "Revenge Trades Détectés",
            "records": "Records",
            "result": "Résultat :",
            "tiltWarning": "Après 2 pertes consécutives, ton WR chute. Tu es en mode tilt. STOP immédiat recommandé.",
            "loadingMTF": "Chargement des indicateurs MTF (RSI + VMC)...",
            "loadingVMC": "Chargement VMC Oscillator...",
            "loadingData": "Chargement des données...",
            "rsiOverbought": "RSI surachat",
            "rsiOversold": "RSI survente",
            "macdBullish": "MACD haussier fort",
            "macdBearish": "MACD baissier fort",
            "vmcBullish": "VMC haussier",
            "vmcBearish": "VMC baissier",
            "biasBullish": "Bias haussier",
            "biasBearish": "Bias baissier",
            "biasNeutral": "Bias neutre",
            "selectAssetToAnalyze": "Sélectionne un actif et appuie sur ↻ pour analyser",
        ],
        .english: [
            "title": "Advanced Trading Journal",
            "subtitle": "Analyze your Long and Short performance by system",
            "dashboard": "Dashboard",
            "systems": "Systems",
            "trades": "Trades",
            "exchanges": "Exchanges",
            "newTrade": "New Trade",
            "newSystem": "New System",
            "detailed": "Detailed",
            "flash": "Flash",
            "date": "Date",
            "asset": "Asset",
            "type": "Type",
            "entryPrice": "Entry Price",
            "exitPrice": "Exit Price",
            "quantity": "Quantity",
            "leverage": "Leverage",
            "orderType": "Order Type",
            "system": "System",
            "session": "Session",
            "add": "Add",
            "cancel": "Cancel",
            "mainMetrics": "Main Metrics",
            "winRate": "Win Rate",
            "totalPnL": "Total P&L",
            "payoffRatio": "Payoff Ratio",
            "fees": "Fees",
            "advancedMetrics": "Advanced Metrics",
            "maxDrawdown": "Max Drawdown",
            "sharpeRatio": "Sharpe Ratio",
            "expectancy": "Expectancy",
            "bestStreak": "Best Streak",
            "longPerf": "LONG Performance",
            "shortPerf": "SHORT Performance",
            "avgWin": "Avg Win",
            "pnlCurve": "P&L Curve",
            "perfBySession": "Performance by Session",
            "perfByAsset": "Performance by Asset",
            "long": "Long",
            "short": "Short",
            "taker": "Taker",
            "maker": "Maker",
            "pnlAmount": "P&L ($)",
            "fillAllFields": "Please fill in all fields",
            "exchangeName": "Exchange name",
            "makerFee": "Maker Fee (%)",
            "takerFee": "Taker Fee (%)",
            "priority": "PRIORITY",
            "setPriority": "Set as priority",
            "systemName": "System name",
            "systemExists": "This system already exists",
            "exportCSV": "Export CSV",
            "importCSV": "Import CSV",
            "addSystem": "Add system",
            // Navigation
            "ai": "AI",
            "assistant": "Assistant",
            // Dashboard
            "performanceByDay": "Performance by Day",
            "mondayToSunday": "Monday → Sunday",
            "advancedAnalytics": "Advanced Analytics",
            // Analytics section
            "advancedAnalyticsTitle": "Advanced Analytics",
            "advancedAnalyticsSubtitleDetail": "Analyze your performance in detail",
            "performanceByMonth": "Performance by Month",
            "gains": "Gains",
            "pertes": "Losses",
            "bestMonth": "Best Month",
            "worstMonth": "Worst Month",
            "average": "Average",
            // Analytics tabs
            "tabAnalytics": "Analytics",
            "tabMetrics": "Metrics",
            "tabCalendar": "Calendar",
            // Emotional Summary card titles
            "cardAverageState": "Average State",
            "cardEmotionImpact": "Emotion Impact",
            "cardEmotionalRisk": "Emotional Risk",
            "cardAIAdvice": "AI Advice",
            // Emotional states
            "stateConfident": "Confident",
            "stateStressed": "Stressed",
            "stateAgitated": "Agitated",
            "stateNeutral": "Neutral",
            // Impact states
            "impactInsufficient": "Insufficient",
            "impactHighStress": "High stress",
            "impactHighConf": "High confidence",
            "impactInstability": "Instability",
            "impactBalanced": "Balanced",
            "impactPositive": "Positive",
            "impactNegative": "Negative",
            // Risk states
            "riskCritical": "Critical",
            "riskAttention": "Caution",
            "riskStable": "Stable",
            // Advice states
            "adviceStop": "Stop",
            "advicePause": "Pause",
            "adviceReduce": "Reduce",
            "adviceStudy": "Study",
            "adviceContinue": "Continue",
            // Emotional descriptions
            "descExcellent10": "Excellent performance over last 10 trades",
            "descBalanced10": "Balanced performance over last 10 trades",
            "descDifficult10": "Difficult period over last 10 trades",
            "descNoData": "Not enough data to analyze emotional state",
            "descNoImpactData": "Not enough data to analyze emotional impact",
            "descConsecLoss": "Series of {n} consecutive losses - High emotional stress",
            "descConsecWin": "Series of {n} consecutive wins - High confidence",
            "descVolatility": "High P&L volatility ({v}) - Emotional instability",
            "descBalancedStable": "Balanced performance - Stable emotions",
            "descCorrPositive": "Positive emotions correlated with gains (+{pct}%)",
            "descCorrNegative": "Negative emotions correlated with losses (-{pct}%)",
            "descNoCorrPnl": "No clear correlation between emotions and P&L",
            "descRiskCritical": "Significant loss streak ({n}) - Attention required",
            "descRiskAttention": "Some consecutive losses ({n}) - Stay alert",
            "descRiskStable": "No loss streak - Stable situation",
            "advicePauseDesc": "Step back and analyze your strategies",
            "adviceStudyDesc": "Study your patterns and improve your approach",
            "adviceContinueDesc": "Continue with your current strategy",
            "descEmoPosPercent": "{pct}% positive emotions over {n} entries",
            "descEmoNegPercent": "{pct}% negative emotions over {n} entries",
            "descEmoMixPercent": "{pct}% mixed emotions over {n} entries",
            "emotions": "Emotions",
            "emotionalSummary": "Emotional summary and impact",
            "heatmap": "Heatmap",
            "heatmapPreview": "Preview (4 weeks)",
            "newSession": "New session",
            "sections": "section",
            "sectionsPlural": "sections",
            // Days of the week
            "monday": "Mon",
            "tuesday": "Tue",
            "wednesday": "Wed",
            "thursday": "Thu",
            "friday": "Fri",
            "saturday": "Sat",
            "sunday": "Sun",
            // AI Assistant
            "insights": "Insights",
            "conseils": "Advice",
            "analyse": "Analysis",
            "indicateurs": "Indicators",
            "photo": "Photo",
            "calendar": "Calendar",
            "lastUpdate": "Last update",
            "refresh": "Refresh",
            "refreshing": "Refreshing...",
            "refreshAnalytics": "Refresh AI analytics",
            // Photo Analysis
            "photoAnalysis": "Photo Analysis",
            "photoAnalysisTitle": "PHOTO",
            "photoAnalysisInstructions": "Take a photo or select a chart for automatic AI analysis.",
            "photoAnalysisInstructionsMulti": "Add one or more chart screenshots from different timeframes. The more TFs you provide, the more detailed and accurate the analysis will be.",
            "camera": "Camera",
            "library": "Library",
            "selectedImage": "Selected image",
            "selectedImages": "Selected images",
            "analyzing": "Analyzing...",
            "quickRead": "🔎 Quick market read",
            "marketStructure": "🧱 Market structure",
            "keyZones": "📍 Key zones",
            "trendMomentum": "📈 Trend & Momentum",
            "patterns": "🕯️ Patterns & Candlesticks",
            "indicators": "📊 Indicators",
            "multiTimeframe": "🧭 Multi-Timeframe reading",
            "tradePlan": "🎯 Trade plan",
            "marketPsychology": "🧠 Market psychology",
            "bias": "Bias",
            "entry": "Entry",
            "stopLoss": "Stop Loss",
            "targets": "Targets",
            "confirmation": "Confirmation",
            "invalidation": "Invalidation",
            // Multi-Timeframe Photo Analysis
            "multiTimeframeMode": "MULTI-TF",
            "selectTimeframePhoto": "Select the timeframe",
            "addTimeframePhoto": "Add a photo",
            "analyzeMulti": "Analyze Multi-TF",
            "analyzeSingle": "Analyze",
            "clearAll": "Clear all",
            "multiTimeframeInfo": "Multi-TF mode enabled — The AI will cross-reference analyses across different timeframes for enriched results.",
            "analyzingMultiUT": "Multi-TF analysis in progress...",
            "analyzingSingleUT": "AI analysis in progress...",
            "imagesLoaded": "Images loaded",
            "crossReferencing": "Cross-referencing TFs...",
            "detectingPatterns": "Detecting patterns...",
            "technicalAnalysis": "Technical analysis...",
            "confluenceDetection": "Detecting confluences...",
            "generatingReport": "Generating report",
            "multiTimeframeAnalysis": "Multi-Timeframe Analysis",
            "utCount": "TFs",
            "confluences": "Inter-TF Confluences",
            "identifiedRisks": "Identified risks",
            "alternativeScenario": "Alternative scenario",
            "riskReward": "R:R",
            "reversalZones": "Reversal zones",
            "chooseTimeframe": "Choose the timeframe",
            "chooseTimeframeSubtitle": "Select the TF matching your screenshot",
            "multiScanInProgress": "Multi-TF scan in progress...",
            "singleScanInProgress": "AI scan in progress...",
            "crossReferencingTimeframes": "The AI is cross-referencing analyses across TFs",
            "analyzingPatterns": "The AI is analyzing patterns, levels and structures",
            "apiKeyMissing": "OpenAI API key not configured. Please configure your key in settings.",
            "analyzerInitError": "Unable to initialize the analyzer.",
            "analysisErrorGeneric": "Analysis error:",
            "analysisError": "Analysis error",
            // Menu
            "profile": "Profile",
            "signOut": "Sign out",
            "signIn": "Sign in",
            "signUp": "Sign up",
            "storageSettings": "Storage Settings",
            "manageSubscription": "Manage PRO subscription",
            "upgradeToPro": "Upgrade to PRO",
            "addTrade": "Add trade",
            "addTradeAccessibility": "Add trade",
            // Dashboard supplémentaires
            "performanceByHour": "Performance by Hour",
            "customizableRanges": "Customizable ranges • Add your time slots",
            "modify": "Modify",
            "hourRange": "Hour range",
            "sessionsDescription": "Asia / London / New York • Customizable",
            "hourRanges": "Hour ranges",
            "hourRangesSubtitle": "Add / delete / modify your time slots",
            "sessions": "Sessions",
            "performanceLongShort": "Long / Short Performance",
            "performanceLongShortSubtitle": "Win rate & P&L by direction",
            "deepen": "Deepen",
            "deepenSubtitle": "Detailed analyses • Opens advanced sections",
            "advancedMetricsSubtitle": "Drawdown, Sharpe, expectancy, streaks",
            "advancedAnalyticsSubtitle": "Analytics / metrics / calendar",
            "pnlCurvePreview": "Preview (30 days)",
            "server": "Server",
            
            // NAVIGATION & TABS
            "account": "Account",
            
            // ADDITIONAL METRICS
            "avgLoss": "Avg Loss",
            "totalTrades": "Total Trades",
            "winningTrades": "Winning Trades",
            "losingTrades": "Losing Trades",
            
            // TRADES
            "save": "Save",
            "delete": "Delete",
            "edit": "Edit",
            "tradeAdded": "Trade added successfully",
            "tradeDeleted": "Trade deleted",
            "tradeUpdated": "Trade updated",
            
            // SYSTEMS
            "systemAdded": "System added",
            "systemDeleted": "System deleted",
            
            // EMOTIONS & ANALYTICS
            "emotionalAnalysis": "Emotional Analysis",
            "emotionalJournal": "Emotional Journal",
            "emotionalLoad": "Emotional load",
            "emotionalBalance": "Emotional balance",
            "emotionalCorrelation": "Emotional correlation",
            "emotionImpact": "Emotional impact",
            "emotionCorrelationWithPnL": "Emotion/P&L correlation",
            "stress": "Stress",
            "anxiety": "Anxiety",
            "confidence": "Confidence",
            "fear": "Fear",
            "greed": "Greed",
            "discipline": "Discipline",
            "patience": "Patience",
            "impulsivity": "Impulsivity",
            "lowStress": "Low stress",
            "moderateStress": "Moderate stress",
            "highStress": "High stress",
            
            // MTF INDICATORS
            "mtfDashboard": "MTF Dashboard",
            "timeframes": "Timeframes",
            "selectTimeframe": "Select timeframe",
            "updateTimeframes": "Update timeframes",
            "5m": "5m",
            "15m": "15m",
            "1h": "1h",
            "4h": "4h",
            "1d": "1d",
            "synchronized": "Synchronized",
            
            // RSI
            "rsi": "RSI",
            "rsiDashboard": "RSI Dashboard",
            "oversold": "Oversold",
            "overbought": "Overbought",
            "neutral": "Neutral",
            "rsiValue": "RSI Value",
            
            // Scenario cards & analysis UI
            "bullishScenario": "Bullish Scenario",
            "bearishScenario": "Bearish Scenario",
            "stopLabel": "Stop",
            "objectivesLabel": "Targets",
            "riskLabel": "Risk",
            "potentialLabel": "Potential",
            "technicalAnalysisTitle": "Technical Analysis",
            "riskManagementTitle": "Risk Management",
            "recommendedRisk": "Recommended Risk",
            "support1": "Support 1",
            "resistance1": "Resistance 1",
            "entryType": "Type",
            
            // VMC
            "vmc": "VMC",
            "vmcDashboard": "VMC Dashboard",
            "trend": "Trend",
            "bullish": "Bullish",
            "bearish": "Bearish",
            "ranging": "Ranging",
            "strength": "Strength",
            "weak": "Weak",
            "moderate": "Moderate",
            "strong": "Strong",
            
            // WAVE TREND
            "waveTrend": "Wave Trend",
            "wtDashboard": "WT Dashboard",
            "crossover": "Crossover",
            "divergence": "Divergence",
            "bullishDivergence": "Bullish divergence",
            "bearishDivergence": "Bearish divergence",
            
            // COMBINED INDICATORS
            "combinedIndicators": "Combined Indicators",
            "alignmentScore": "Alignment score",
            "confluence": "Confluence",
            
            // ECONOMIC CALENDAR
            "economicCalendar": "Economic Calendar",
            "upcomingEvents": "Upcoming events",
            "pastEvents": "Past events",
            "impact": "Impact",
            "highImpact": "High impact",
            "mediumImpact": "Medium impact",
            "lowImpact": "Low impact",
            "forecast": "Forecast",
            "previous": "Previous",
            "actual": "Actual",
            "country": "Country",
            "event": "Event",
            "time": "Time",
            "noEventsToday": "No events today",
            "loadingEvents": "Loading events...",
            "refreshCalendar": "Refresh calendar",
            
            // GAMIFICATION
            "challenges": "Challenges",
            "missions": "Missions",
            "badges": "Badges",
            "level": "Level",
            "xp": "XP",
            "experience": "Experience",
            "progress": "Progress",
            "rewards": "Rewards",
            "unlocked": "Unlocked",
            "locked": "Locked",
            "complete": "Complete",
            "completed": "Completed",
            "inProgress": "In progress",
            "notStarted": "Not started",
            "streak": "Streak",
            "dailyStreak": "Daily streak",
            "currentStreak": "Current streak",
            
            // SOCIAL & VERIFICATION
            "socialVerification": "Social Verification",
            "verifyAccount": "Verify account",
            "verified": "Verified",
            "notVerified": "Not verified",
            "connectSocialAccount": "Connect social account",
            "shareResults": "Share results",
            "leaderboard": "Leaderboard",
            "rank": "Rank",
            "followers": "Followers",
            "following": "Following",
            
            // ALERTS & NOTIFICATIONS
            "alerts": "Alerts",
            "createAlert": "Create alert",
            "editAlert": "Edit alert",
            "deleteAlert": "Delete alert",
            "alertName": "Alert name",
            "condition": "Condition",
            "price": "Price",
            "priceAbove": "Price above",
            "priceBelow": "Price below",
            "volume": "Volume",
            "triggerPrice": "Trigger price",
            "triggered": "Triggered",
            "active": "Active",
            "inactive": "Inactive",
            "notifications": "Notifications",
            "pushNotifications": "Push notifications",
            "emailNotifications": "Email notifications",
            "soundEnabled": "Sound enabled",
            
            // ADVANCED STATS
            "profitFactor": "Profit Factor",
            "riskRewardRatio": "Risk/Reward Ratio",
            "averageRR": "Avg R:R",
            "recoveryFactor": "Recovery Factor",
            "kellyPercentage": "Kelly %",
            "consistency": "Consistency",
            "volatility": "Volatility",
            "standardDeviation": "Standard Deviation",
            "calmarRatio": "Calmar Ratio",
            "sortinoRatio": "Sortino Ratio",
            
            // SETTINGS
            "settings": "Settings",
            "aiSettings": "AI Settings",
            "language": "Language",
            "selectLanguage": "Select Language",
            "theme": "Theme",
            "appearance": "Appearance",
            "darkMode": "Dark mode",
            "lightMode": "Light mode",
            "automatic": "Automatic",
            "currency": "Currency",
            "timezone": "Timezone",
            "dateFormat": "Date format",
            "timeFormat": "Time format",
            "chartType": "Chart type",
            "candlestick": "Candlestick",
            "line": "Line",
            "bar": "Bar",
            "area": "Area",
            
            // AUTH
            "email": "Email",
            "password": "Password",
            "confirmPassword": "Confirm Password",
            "forgotPassword": "Forgot Password?",
            "resetPassword": "Reset",
            "createAccount": "Create Account",
            "alreadyHaveAccount": "Already have an account?",
            "dontHaveAccount": "Don't have an account?",
            
            // SUBSCRIPTION
            "subscription": "Subscription",
            "freePlan": "Free Plan",
            "proPlan": "PRO Plan",
            "subscribe": "Subscribe",
            
            // FULL DAYS
            "mondayFull": "Monday",
            "tuesdayFull": "Tuesday",
            "wednesdayFull": "Wednesday",
            "thursdayFull": "Thursday",
            "fridayFull": "Friday",
            "saturdayFull": "Saturday",
            "sundayFull": "Sunday",
            
            // TIME
            "today": "Today",
            "yesterday": "Yesterday",
            "thisWeek": "This week",
            "lastWeek": "Last week",
            "thisMonth": "This month",
            "lastMonth": "Last month",
            "all": "All",
            
            // MESSAGES & ERRORS
            "error": "Error",
            "success": "Success",
            "warning": "Warning",
            "loading": "Loading...",
            "noData": "No data",
            "noResults": "No results",
            "tryAgain": "Try again",
            "close": "Close",
            "confirm": "Confirm",
            "yes": "Yes",
            "no": "No",
            "ok": "OK",
            
            // SEARCH & FILTERS
            "search": "Search",
            "filter": "Filter",
            "sort": "Sort",
            "sortBy": "Sort by",
            "filterBy": "Filter by",
            "none": "None",
            "select": "Select",
            "clear": "Clear",
            
            // SECURITY
            "security": "Security",
            "privacy": "Privacy",
            "biometricAuth": "Biometric auth",
            "faceID": "Face ID",
            "touchID": "Touch ID",
            "pinCode": "PIN code",
            "changePIN": "Change PIN",
            "twoFactorAuth": "Two-factor auth",
            "enable": "Enable",
            "disable": "Disable",
            "deleteAccount": "Delete account",
            "deleteAccountWarning": "This action is irreversible",
            
            // IMPORT/EXPORT
            "import": "Import",
            "export": "Export",
            "backup": "Backup",
            "restore": "Restore",
            "downloadBackup": "Download backup",
            "uploadBackup": "Upload backup",
            "selectFile": "Select file",
            "lastBackup": "Last backup",
            "autoBackup": "Auto backup",
            "backupFrequency": "Backup frequency",
            "daily": "Daily",
            "weekly": "Weekly",
            "monthly": "Monthly",
            "dataExport": "Data Export",
            "dataImport": "Data Import",
            
            // CHARTS
            "chartSettings": "Chart settings",
            "showGrid": "Show grid",
            "showVolume": "Show volume",
            "showMA": "Show MA",
            "showBollinger": "Show Bollinger",
            "showRSI": "Show RSI",
            "showMACD": "Show MACD",
            "colorScheme": "Color scheme",
            "greenRed": "Green/Red",
            "blueOrange": "Blue/Orange",
            "custom": "Custom",
            
            // HELP & SUPPORT
            "help": "Help",
            "support": "Support",
            "faq": "FAQ",
            "tutorials": "Tutorials",
            "contactUs": "Contact us",
            "reportBug": "Report bug",
            "featureRequest": "Feature request",
            "documentation": "Documentation",
            "termsOfService": "Terms of service",
            "privacyPolicy": "Privacy policy",
            "version": "Version",
            "buildNumber": "Build number",
            
            // OTHERS
            "local": "Local",
            "sync": "Sync",
            "syncing": "Syncing...",
            "offline": "Offline",
            "online": "Online",
            
            // SPECIFIC VIEW TEXTS (automatically extracted)
            "addTrades": "Add trades",
            "aiAnalysis": "AI Analysis",
            "analysisWaiting": "Analysis waiting...",
            "analysisInProgress": "Analysis in progress...",
            "advancedTechnicalAnalysis": "Advanced technical analysis in progress...",
            "emotionalAnalyses": "Emotional Analyses",
            "badge": "Badge",
            "loadingWaveTrend": "Loading Wave Trend oscillator...",
            "loadingEnrichedData": "Loading enriched data...",
            "loadingMTFIndicators": "Loading MTF indicators (RSI + VMC)...",
            "loadingIndicators": "Loading indicators...",
            "loadingProducts": "Loading products...",
            "aiChat": "AI Chat",
            "aiCoach": "AI Coach",
            "configuration": "Configuration",
            "curve": "Curve",
            "alertDetail": "Alert Detail",
            "tradeDetail": "Trade Detail",
            "details": "Details",
            "exportImport": "Export / Import",
            "exporting": "Exporting...",
            "filters": "Filters",
            "advancedFilters": "Advanced Filters",
            "generatingHeatmap": "Generating heatmap...",
            "performanceHeatmaps": "Performance Heatmaps",
            "history": "History",
            "aiAndOpenAI": "AI & OpenAI",
            "importing": "Importing...",
            "aiAnalyzingChart": "AI is analyzing your chart...",
            "mission": "Mission",
            "storageMode": "Storage mode",
            "editExchange": "Edit Exchange",
            "editTrade": "Edit Trade",
            "myAccount": "My account",
            "newExchange": "New Exchange",
            "pnlWithContext": "P&L with Context",
            "alertSettings": "Alert Settings",
            "referral": "Referral",
            "moreOptions": "More options",
            "saveFilter": "Save filter",
            "statistics": "Statistics",
            "storage": "Storage",
            "writeMessage": "Write a message...",
            "emotionsPerformance": "Emotions ↔ Performance",
            "waveTrendOscillator": "Wave Trend Oscillator",
            "DonnesTechniques": "Technical Data",
            "alertes": "Alerts",
            "conf": "Conf.",
            "extrmesBas": "Extreme Lows",
            "extrmesHauts": "Extreme Highs",
            "global": "Global",
            "guide": "Guide",
            "intqualityscore": "Quality Score",
            "intsnapshotconfluencepercent": "Confluence",
            "lgende": "Legend",
            "momentum": "Momentum",
            "mtf": "MTF",
            "pourLesCurieux": "For the Curious",
            "score": "Score",
            "scoreCombin": "Combined Score",
            "signal": "Signal",
            "signalGlobal": "Global Signal",
            "signaux": "Signals",
            "synthse": "Summary",
            "unitDeTemps": "Timeframe",
            "volume24h": "24h Volume",
            "btcusdt": "BTCUSDT",
            "disponibleAvecLabonnementPremium": "Available with Premium subscription",
            "labelvalue100": "Label (Value /100)",
            "scoremotionnelemotionscore100": "Emotional Score",
            "name": "Name",
            "499moisAnnulationToutMoment": "$4.99/month · Cancel anytime",
            "Obligations": "Bonds",
            "Recommandation": "Recommendation",
            "Recommandations": "Recommendations",
            "Records": "Records",
            "accdezToutesLesFonctionnalitsAvancesAvecLePassPro": "Access all advanced features with the Pro Pass",
            "accsDepuisNimporteO": "Access From Anywhere",
            "actions": "Actions",
            "actionsRapides": "Quick Actions",
            "afficherLeContextemotionnel": "Show Emotional Context",
            "agrgation": "Aggregation",
            "ajouterUneEmotion": "Add an Emotion",
            "aperu": "Preview",
            "appareil": "Device",
            "apple": "Apple",
            "aprs": "After",
            "aucunBadge": "No Badge",
            "aucunBadgeDbloqu": "No Badge Unlocked",
            "aucunDfiDisponible": "No Challenge Available",
            "aucunFilleulPourLinstant": "No Referrals Yet",
            "aucunInsightDisponiblePourCettePriode": "No insight available for this period",
            "aucunTrade": "No Trade",
            "aucunTradeTrouv": "No Trade Found",
            "aucuneEntre": "No Entry",
            "aucuneProgression": "No Progress",
            "aucuntatEnregistr": "No State Recorded",
            "aucunvnementTrouv": "No Event Found",
            "aucunvnementXp": "No XP Event",
            "avant": "Before",
            "avecContextemotionnelEnArrireplan": "With emotional context in background",
            "badgeDbloqu": "Badge Unlocked!",
            "badgesParRaret": "Badges by Rarity",
            "badgesRcents": "Recent Badges",
            "bilanmotionnel": "Emotional Summary",
            "bonjour": "Hello",
            "calculEnCours": "Calculating...",
            "calculerPl": "Calculate P&L",
            "calculsAutomatiques": "Automatic calculations",
            "cart": "Dismissed",
            "cesFiltresSerontAppliqusParDfautLorsDeLouvertureDeLaListeDesAlertes": "These filters will be applied by default when opening the alerts list",
            "cesStatistiquesVousDonnentUneVueDensembleDeVosDonnesStockes": "These statistics give you an overview of your stored data",
            "changerLaPhoto": "Change Photo",
            "chargemotionnelle": "Emotional Load",
            "chargemotionnelle0100": "Emotional Load (0-100)",
            "choisirLeModeDeStockage": "Choose Storage Mode",
            "choisissezEntreLeStockageLocalprivOuFirebasesynchronis": "Choose between local storage (private) or Firebase (synced)",
            "choisissezVotreAbonnement": "Choose Your Subscription",
            "choisissezVotreMthodeDajout": "Choose your entry method",
            "codeDeVrification": "Verification Code",
            "commencezTraderPourGagnerDeLxp": "Start trading to earn XP",
            "commentAccderAuPrestige": "How to access prestige",
            "commentDbloquer": "How to Unlock",
            "comparezVosmotionsEtVosPerformancesQuotidiennes": "Compare your emotions and daily performance",
            "conditions": "Conditions",
            "configurezCetteUrlDansTradingviewPourRecevoirDesAlertesAutomatiquementLaClSecrteDoitCorrespondreCelleConfigureSurLeServeur": "Configure this URL in TradingView to receive alerts automatically. The secret key must match the one configured on the server.",
            "connectezvousPourAccderVotreJournalDeTrading": "Sign in to access your trading journal",
            "conseilPro": "Pro Tip",
            "contexte": "Context",
            "continuer": "Continue",
            "copier": "Copy",
            "corrlationmotionperformance": "Emotion/Performance Correlation",
            "courbe": "Curve",
            "courbeDePlCumul": "Cumulative P&L Curve",
            "crationDeTrade": "Trade Creation",
            "crerUnTrade": "Create a Trade",
            "dbloquLe": "Unlocked on",
            "dbloquezDesBadgesEnCompltantDesDfis": "Unlock badges by completing challenges",
            "dbloquezToutLePotentiel": "Unlock Full Potential",
            "dcomposition": "Breakdown",
            "dernireEntre": "Last Entry",
            "description": "Description",
            "dfisActifs": "Active Challenges",
            "direction": "Direction",
            "donnesMigrer": "Data to Migrate",
            "donnesTechniques": "Technical Data",
            "dupliquerLeTrade": "Duplicate Trade",
            "enContinuantTuUtilisesFirebaseAuthentication": "By continuing, you use Firebase Authentication",
            "enregistrezUnTradeEnQuelquesSecondes": "Record a trade in seconds",
            "enregistrezVosTransactionsDeTrading": "Record your trading transactions",
            "enregistrezVotretatmotionnelActuel": "Record your current emotional state",
            "entrezLeCode": "Enter the Code",
            "essayerProGratuit": "Try Pro for Free",
            "europe": "Europe",
            "exchangeParDfaut": "Default Exchange",
            "exit": "Exit",
            "exporterLesDonnes": "Export Data",
            "filtresParDfaut": "Default Filters",
            "fonctionnalitsPro": "Pro Features",
            "galerie": "Gallery",
            "gnral": "General",
            "google": "Google",
            "heatmapDePerformance": "Performance Heatmap",
            "heuresSilencieuses": "Quiet Hours",
            "historiqueXpRcent": "Recent XP History",
            "impactSurLaPerformance": "Impact on Performance",
            "importerLesDonnes": "Import Data",
            "impossibleDeChargerLesProduits": "Unable to Load Products",
            "inclusDansLePassPro": "Included in Pro Pass",
            "informations": "Information",
            "instructions": "Instructions",
            "intense": "Intense",
            "intensit": "Intensity",
            "interprtation": "Interpretation",
            "leModeLocalStockeLesDonnesUniquementSurVotreAppareilLeModeFirebaseSynchroniseVosDonnesDansLeCloud": "Local mode stores data only on your device. Firebase mode syncs your data to the Cloud.",
            "leStockageLocalGardeVosAlertesPrivesSurCetAppareilUniquement": "Local storage keeps your alerts private on this device only",
            "lesAlertesSontStockesUniquementSurCetAppareilEllesNeSerontPasSynchronisesAvecDautresAppareils": "Alerts are stored only on this device. They will not be synced with other devices.",
            "levier": "Leverage",
            "lgendemotionnelle": "Emotional Legend",
            "lissePourRvlerLaTendanceSansJugement": "Smoothed to reveal trends, without judgment",
            "lues": "Read",
            "message": "Message",
            "mexc": "MEXC",
            "migration": "Migration",
            "migrationDesDonnes": "Data Migration",
            "migrezVosDonnesEntreLesDiffrentsModesDeStockageCetteOprationPeutPrendreQuelquesMinutes": "Migrate your data between storage modes. This operation may take a few minutes.",
            "modeDeStockage": "Storage Mode",
            "mom": "Mom.",
            "momentumTrsFortRisqueDeRetournement": "Very strong momentum, reversal risk",
            "motion": "Emotion",
            "motionDominante": "Dominant Emotion",
            "motionnel": "Emotional",
            "motionsPerformance": "Emotions ↔ Performance",
            "mthodesDeVrification": "Verification Methods",
            "mtrique": "Metric",
            "mtriquesAvances": "Advanced Metrics",
            "mtriquesCls": "Key Metrics",
            "multiappareils": "Multi-device",
            "niveauDeContrle": "Control Level",
            "niveauDePrestige": "Prestige Level",
            "niveaux": "Levels",
            "number": "Number",
            "options": "Options",
            "ouDbloquezInstantanmentAvecLePassPro": "Or unlock instantly with the Pro Pass",
            "partager": "Share",
            "partagezVotreCodePourInviterDesAmisEtGagnerDesRcompenses": "Share your code to invite friends and earn rewards",
            "pasEncoreAssezDentresAftertradePourCalculerLaCharge": "Not enough after-trade entries to calculate the load",
            "pasEncoreDeDonnesDeCorrlation": "No correlation data yet",
            "pasEncoreDeDonnesPl": "No P&L data yet",
            "pasEncoreDeDonnesmotionnelles": "No emotional data yet",
            "passezAuNiveauSuprieurAvecLePassPro": "Level up with the Pro Pass",
            "pendantLesHeuresSilencieusesSeulesLesAlertesDeHautePrioritSerontEnvoyes": "During quiet hours, only high priority alerts will be sent",
            "performancePl": "P&L Performance",
            "performanceTempsRel": "Real-time Performance",
            "pl": "P&L",
            "plCumul": "Cumulative P&L",
            "plCumulatif7Jours": "7-Day Cumulative P&L",
            "plDuJour": "Today's P&L",
            // CurveMode titles
            "curveModePnl": "P&L",
            "curveModeEmotional": "Emotional load",
            "curveModeCorrelation": "Correlation",
            "curveModePnlContext": "P&L + Context",
            // Curve subtitles
            "curveSubPnl": "Result (P&L)",
            "curveSubEmotional": "Context (pressure)",
            "curveSubCorrelation": "P&L × emotion",
            "curveSubPnlContext": "P&L + emotional context",
            // Curve helper texts
            "curveHelperPnl": "This curve shows the cumulative evolution of your results.",
            "curveHelperEmotional": "Emotional load represents mental pressure, not performance.",
            "curveHelperCorrelation": "This view lets you observe whether losses or gains occur during high emotional pressure.",
            "curveHelperPnlContext": "Bars represent the result per period. The curve shows the emotional pressure level.",
            // Insights toggle
            "showInsights": "View analysis",
            "hideInsights": "Hide analysis",
            // Correlation labels
            "corrStrong": "Strong correlation",
            "corrModerate": "Moderate correlation",
            "corrWeak": "Weak correlation",
            "corrNone": "No correlation",
            "corrNegWeak": "Weak negative correlation",
            "corrNegModerate": "Moderate negative correlation",
            "corrNegStrong": "Strong negative correlation",
            // Insight texts (DashboardAnalyticsCompute)
            "insightPnlLastSegmentUp": "About {pct}% of the performance is built at the end of the period.",
            "insightPnlLastSegmentNet": "About {pct}% of the net move is concentrated at the end of the period.",
            "insightPnlTrendUp": "The curve is mostly upward over this period.",
            "insightPnlTrendDown": "The curve is mostly downward over this period.",
            "insightPnlDrawdown": "The longest drawdowns occur at the {placement} of the period.",
            "insightEmoCalmShare": "{pct}% of the time is spent in the Calm / Alert zone.",
            "insightEmoTensionShare": "Pressure exceeds Tension on {pct}% of the period.",
            "insightEmoSpikes": "Emotional spikes are short but frequent.",
            "insightCorrLossHighPressure": "{pct}% of losses occur when pressure exceeds Tension.",
            "insightCorrGainsCalm": "Gains are mainly achieved in the Calm zone.",
            "insightCorrPerformancePressure": "Performance tends to drop when pressure exceeds Tension.",
            "periodStart": "start",
            "periodEnd": "end",
            "plPriode": "Period P&L",
            "plQuotidien": "Daily P&L",
            "plateforme": "Platform",
            "pointSlectionn": "Selected Point",
            "prcdent": "Previous",
            "presetsRapides": "Quick Presets",
            "pressionmotionnelle0100": "Emotional Pressure (0-100)",
            "prestige": "Prestige",
            "prestigeMaximumAtteint": "Maximum Prestige Reached",
            "priode": "Period",
            "priodesRapides": "Quick Periods",
            "progression": "Progress",
            "progressionVersLePrestige": "Progress Towards Prestige",
            "prtrade": "Per Trade",
            "prvision": "Forecast",
            "reco": "Reco.",
            "recommandation": "Recommendation",
            "recommandations": "Recommendations",
            "recommandationsGnrales": "General Recommendations",
            "rejoindre": "Join",
            "rel": "Actual",
            "reroll": "Reroll",
            "rerolls": "Rerolls",
            "restaurationComplte": "Full Restore",
            "restaurerLesAchats": "Restore Purchases",
            "rleDordre": "Order Rule",
            "rsumQuotidien": "Daily Summary",
            "sauvegardeComplte": "Full Backup",
            "sauvegardeEtRestauration": "Backup and Restore",
            "scnarios": "Scenarios",
            "scoreDeDiscipline": "Discipline Score",
            "sentiment": "Sentiment",
            "siConsensus": "If consensus",
            "signalLine": "Signal Line",
            "slectionMultipleDeSymboles": "Multiple Symbol Selection",
            "slectionnezLesTimeframes": "Select Timeframes",
            "slectionnezUnePhotoDeGraphique": "Select a chart photo",
            "source": "Source",
            "stabilitmotionnelle": "Emotional Stability",
            "statistiques": "Statistics",
            "statistiquesDuJour": "Today's Statistics",
            "statistiquesGlobales": "Global Statistics",
            "statutDeLecture": "Read Status",
            "step": "Step",
            "stockageDesAlertes": "Alert Storage",
            "stockageLocalUniquement": "Local Storage Only",
            "surprise": "Surprise",
            "svrit": "Severity",
            "symbole": "Symbol",
            "symbolesRcents": "Recent Symbols",
            "tags": "Tags",
            "tapes": "Steps",
            "termin": "Completed",
            "timelineDes10DerniersJours": "Last 10 Days Timeline",
            "total": "Total",
            "touchezEtGlissezSurLeGraphiquePourExplorerLesDonnes": "Touch and drag on the chart to explore data",
            "touchezGlissez": "Touch & drag",
            "touchezUneCase": "Tap a cell",
            "tous": "All",
            "toutes": "All",
            "toutesVosDonnesSerontExportes": "All your data will be exported",
            "tradeLi": "Linked Trade",
            "uidFirebase": "Firebase UID",
            "valeurMax": "Max Value",
            "valeurMin": "Min Value",
            "valeurs": "Values",
            "valider": "Validate",
            "voirTout": "See All",
            "volutionDeLintensit": "Intensity Evolution",
            "volutionXp7Jours": "7-Day XP Evolution",
            "vosDonnesToujoursJour": "Your Data Always Up-to-date",
            "vosFilleuls": "Your Referrals",
            "vousNavezPasReuLeCode": "Didn't receive the code?",
            "zonesDeVigilance": "Vigilance Zones",
            "zonesDeVigilanceAvecLissagePourRvlerLesTendances": "Vigilance zones with smoothing to reveal trends",
            // AIAssistantView - Insights tab
            "predictionNextTrade": "Next Trade Prediction",
            "basedOnHistory": "Based on your history and current context",
            "winProbability": "Win probability",
            "maxLoss": "Max loss",
            "maxGain": "Max gain",
            "expectedValue": "Expected value",
            "influencingFactors": "Influencing factors",
            "recommendation": "Recommendation",
            "planConsistency": "Plan Consistency",
            "respectStrategy": "Respect your strategy",
            "adherence": "Adherence",
            "aiRecommendations": "AI Recommendations",
            "optimalTiming": "Optimal Timing",
            "bestMomentsToTrade": "Best moments to trade",
            "bestHour": "Best hour",
            "avoidHour": "Avoid",
            "bestDay": "Best day",
            "recommendations": "Recommendations",
            "preferablyTrade": "Trade preferably between",
            // AIAssistantView - Advice tab
            "currentStatus": "Current Status",
            "edgeScore": "Edge Score",
            "priorityAction": "Priority Action",
            "recommendedAction": "Recommended action",
            "optimalWindow": "Optimal Window",
            "timingEdge": "Your edge timing",
            "dailyFocus": "Daily Focus",
            "prioritySetup": "Priority setup",
            "influencingFactorsPlural": "Influencing Factors",
            "evaluatingConditions": "Evaluating your conditions",
            "currentEdgeAdvantages": "Current advantages",
            "riskToWatch": "Risks to watch",
            "edgeScoreExplanation": "How is your Edge Score calculated?",
            "edgeScoreFormula": "Score = 50 +",
            "baselinePoints": "Calculation starts at 50 base points, then adjustments are applied based on your current conditions:",
            "decisionLevels": "Decision levels",
            "factorsInfluencingEdge": "Factors influencing your Edge",
            // AIAssistantView - Indicators tab
            "tiltDetected": "TILT ALERT DETECTED",
            "streakAndTiltAnalysis": "Streak & Tilt Analysis",
            "behaviorAfterTrades": "Behavior after trades",
            "behaviorAfterWinsLosses": "Behavior after wins/losses",
            "revengeTradesDetected": "Revenge Trades Detected",
            "records": "Records",
            "result": "Result:",
            "tiltWarning": "After 2 consecutive losses, your WR drops. You are in tilt mode. STOP immediately recommended.",
            "loadingMTF": "Loading MTF indicators (RSI + VMC)...",
            "loadingVMC": "Loading VMC Oscillator...",
            "loadingData": "Loading data...",
            "rsiOverbought": "RSI overbought",
            "rsiOversold": "RSI oversold",
            "macdBullish": "MACD strongly bullish",
            "macdBearish": "MACD strongly bearish",
            "vmcBullish": "VMC bullish",
            "vmcBearish": "VMC bearish",
            "biasBullish": "Bullish bias",
            "biasBearish": "Bearish bias",
            "biasNeutral": "Neutral bias",
            "selectAssetToAnalyze": "Select an asset and press ↻ to analyze",
        ]
    ]
}
